version: '3.0'
services:
  mongo:
    image: 'mongo:6.0'
    restart: 'always'
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=example"
    ports:
      - '27017:27017'
  crud:
    restart: 'always'
    ports:
      - '3004:3004'
    build:
      context: .
      dockerfile: Dockerfile

