# -*- restclient -*-

# GET data
GET http://localhost:3004/products
Accept: application/json
Authorization: 619806ebd901bc53b9783241

# POST new endpoint
POST http://localhost:3004/products
Content-Type: application/json
Authorization: 619806ebd901bc53b9783241
{
"name": "iron pan",
"color": "gray",
"weight": "2kg"
}

# GET specific data by id
GET http://localhost:3004/products/637271044f9fe8013bcf25be
Accept: application/json
Authorization: 619806ebd901bc53b9783241

# Get all data for endpoint /pets of user with id
GET http://localhost:3004/products
Accept: application/json
Authorization: 619806ebd901bc53b9783241

DELETE http://localhost:3004/products/637266904f9fe8013bcf25bb
Accept: application/json
Authorization: 619806ebd901bc53b9783241

